### ISSUE TITLE
Poor readability in vimdiff with cursorline

### ISSUE THREAD

**Issue by AndroidOatmeal** [morhetz/gruvbox#40] opened 2014-12-17 20:53 UTC
Hello,

I've noticed that when I have `:set cursorline` in my vimrc and I try to vimdiff something, my cursor line makes diffed text quite hard to read. See picture for an example.

Any ideas on how to solve this?

![screen shot 2014-12-17 at 15 48 55](https://cloud.githubusercontent.com/assets/3051042/5478729/bcc71dde-8604-11e4-9e63-2e25a4b5b7ad.png)

**Comment by AndroidOatmeal** [comment] 2015-01-12 16:27
If it helps anyone, I've come up with a workaround that disables cursorline in vimdiff mode. I added the following to my vimrc:
```
if !&diff
    set cursorline
endif
```

**Comment by ikcalB** [comment] 2015-03-09 17:20
+1 having the exact same Problem w/ xfce4-terminal.

imho, the lightish gray, that is normally a perfect cursorline color, has very poor contrast to fg/text color (black?)  when vimdiffing.

**Comment by morhetz** [comment] 2015-03-10 04:59
@ikcalB I'm sorry, I can't reproduce it with xfce4-terminal 0.6.3

vim from *buntu lts 14.04:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)

**Comment by ikcalB** [comment] 2015-03-10 11:36
Debian Jessie (testing)
vim 7.4.488:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 30 2014 04:22:27)
Included patches: 1-488
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             -ebcdic          +localmap        +printer         +title
+arabic          +emacs_tags      +lua             +profile         +toolbar
+autocmd         +eval            +menu            +python          +user_commands
+balloon_eval    +ex_extra        +mksession       -python3         +vertsplit
+browse          +extra_search    +modify_fname    +quickfix        +virtualedit
++builtin_terms  +farsi           +mouse           +reltime         +visual
+byte_offset     +file_in_path    +mouseshape      +rightleft       +visualextra
+cindent         +find_in_path    +mouse_dec       +ruby            +viminfo
+clientserver    +float           +mouse_gpm       +scrollbind      +vreplace
+clipboard       +folding         -mouse_jsbterm   +signs           +wildignore
+cmdline_compl   -footer          +mouse_netterm   +smartindent     +wildmenu
+cmdline_hist    +fork()          +mouse_sgr       -sniff           +windows
+cmdline_info    +gettext         -mouse_sysmouse  +startuptime     +writebackup
+comments        -hangul_input    +mouse_urxvt     +statusline      +X11
+conceal         +iconv           +mouse_xterm     -sun_workshop    -xfontset
+cryptv          +insert_expand   +multi_byte      +syntax          +xim
+cscope          +jumplist        +multi_lang      +tag_binary      +xsmp_interact
+cursorbind      +keymap          -mzscheme        +tag_old_static  +xterm_clipboard
+cursorshape     +langmap         +netbeans_intg   -tag_any_white   -xterm_save
+dialog_con_gui  +libcall         +path_extra      +tcl             +xpm
+diff            +linebreak       +perl            +terminfo
+digraphs        +lispindent      +persistent_undo +termresponse
+dnd             +listcmds        +postscript      +textobjects
```
I could upload another screenshot (which would look almost identical to the above)
What does it look like on your side!? @morhetz

**Comment by morhetz** [comment] 2015-03-11 21:48
@ikcalB 
Well that's urxvt actually, but xfce-terminal would be just the same
![screenshot - 12 03 2015 - 00 43 09](https://cloud.githubusercontent.com/assets/554231/6607587/0c081202-c851-11e4-8160-784250eff8d1.png)
There is just blinking cursor, color line is only visible at the line-number columns.
I'm confused a little bit. Could you try reproducing this with some clean vimrc like [tpope's vim-sensible](https://github.com/tpope/vim-sensible)?

**Comment by ikcalB** [comment] 2015-03-25 10:00
@morhetz 
tracked it down to `:set cursorline` (is really handy imho)
any chance to fix that by either
- having custom cursorline/textstyle at the position of the cursurline? (depending on the textstyle without the cursorline)
- or disabling cursorline when in diff-mode?

**Comment by morhetz** [comment] 2015-09-04 18:04
@AndroidOatmeal, @ikcalB:
That issue should be finally fixed with the latest release

**Closed** 2015-09-04 18:08 UTC

**Comment by ikcalB** [comment] 2015-09-09 10:55
@morhetz Thank you for your effort! Now, the cursorline is "behind" the highlighting of the diff - it seems to vanish.

Can you think of a good possibility, to have a cursorline with good visibility in diff mode?

**Comment by morhetz** [comment] 2015-09-09 11:11
@ikcalB That's how it currently works as I suppose that fixes issue
![Imgur](http://i.imgur.com/gpfZ5E9.png)

Is highlighted line number not enough to distinguish current line?
Currently I have no good idea on how to have a cursorline AND highlighted bg (diff mode) at the same time.
