### ISSUE TITLE
Airline theme wrong colors in tmux

### ISSUE THREAD

**Issue by persep** [morhetz/gruvbox#233] opened 2018-03-14 15:38 UTC
This is my vi in the terminal:
![Imgur](https://i.imgur.com/OSkQh23.jpg)

And this is the same vi inside tmux:
![Imgur](https://i.imgur.com/liwSzrQ.jpg)

The colors from the default airline theme are changed.
My  .vimrc is:
    
    " Plugins will be downloaded under the specified directory.                                     
    call plug#begin('~/.vim/plugged')                                                               

    " Declare the list of plugins.                                                                  
    Plug 'vim-airline/vim-airline'                                                                  
    Plug 'morhetz/gruvbox'                                                                          
                                                                                               
    " List ends here. Plugins become visible to Vim after this call.                                
    call plug#end()                                                                                                                                                                               
    set number      "Precede each line with its line number                                        
    syntax enable   "Enable syntax highlighting                                                    
    set background=dark                                                                            
    colorscheme gruvbox                                                                            
    set t_ut=                                                                                      
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"                                                         
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"                                                         
    set termguicolors

Both return `gruvbox` to the command `:AirlineTheme`outside and inside tmux.
`$TERM` is `xterm-256color` in the terminal  and `tmux-256color`  inside tmux.
I's using Vim 8 1567 and tmux 2.1 (also tried tmux 2.6 but I got the same problem) in Ubuntu for windows

**Comment by horseinthesky** [comment] 2018-03-14 18:23
Add this t your `.tmux.conf`
```
set -g default-terminal "screen-256color"
```

Should fix

**Comment by persep** [comment] 2018-03-14 20:46
Thanks for your suggestion but as I said the `$TERM` variable already shows `screen-256color`and I also tried `tmux-256color` but didn't work . Anyway , my .tmux.conf is:

    set -g default-terminal "screen-256color"               
    set -sg escape-time 0

**Comment by persep** [comment] 2018-03-15 08:01
It look like I'm not the only one https://github.com/morhetz/gruvbox/issues/98#issuecomment-317405479

**Comment by morhetz** [comment] 2018-03-15 08:24
@persep that's tmux issue unrelated to gruvbox
mind if I close this issue as a duplicate of #98?
I would like to help you with this one though unfortunately I don't have enough spare time

**Comment by persep** [comment] 2018-03-15 08:31
ok go ahead

**Closed** 2018-03-15 08:32 UTC

**Comment by HarrisonLee1998** [comment] 2020-07-30 08:37
> Add this to your `.tmux.conf`
> 
> ```
> set -g default-terminal "screen-256color"
> ```
> 
> Should fix

it works!

**Comment by nicoandresr** [comment] 2020-08-30 23:40
At least works after hours trying, the solutions added this to my `.tmux.conf`

```
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc" 
```
